/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliticasRouteImport } from './routes/politicas'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as BaixarRouteImport } from './routes/baixar'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssinarRetornoRouteImport } from './routes/assinar.retorno'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as ApiPublicSignupRouteImport } from './routes/api/public/signup'
import { Route as ApiPublicWhatsappSignupCallbackRouteImport } from './routes/api/public/whatsapp.signup-callback'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksDispatchJobsRouteImport } from './routes/api/public/hooks/dispatch-jobs'
import { Route as ApiPublicExtensionQuickRepliesRouteImport } from './routes/api/public/extension/quick-replies'
import { Route as ApiPublicExtensionPairRouteImport } from './routes/api/public/extension/pair'
import { Route as ApiPublicExtensionMetaRouteImport } from './routes/api/public/extension/meta'
import { Route as ApiPublicExtensionFunnelsRouteImport } from './routes/api/public/extension/funnels'
import { Route as ApiPublicExtensionFunnelCardsRouteImport } from './routes/api/public/extension/funnel-cards'
import { Route as ApiPublicExtensionCustomersRouteImport } from './routes/api/public/extension/customers'
import { Route as ApiPublicExtensionCampaignsRouteImport } from './routes/api/public/extension/campaigns'
import { Route as ApiPublicExtensionBillingRouteImport } from './routes/api/public/extension/billing'
import { Route as ApiPublicExtensionWhatsappStatusRouteImport } from './routes/api/public/extension/whatsapp.status'
import { Route as ApiPublicExtensionWhatsappProviderRouteImport } from './routes/api/public/extension/whatsapp.provider'
import { Route as ApiPublicExtensionWhatsappDisconnectRouteImport } from './routes/api/public/extension/whatsapp.disconnect'
import { Route as ApiPublicExtensionWhatsappConnectRouteImport } from './routes/api/public/extension/whatsapp.connect'
import { Route as ApiPublicExtensionWaSyncRouteImport } from './routes/api/public/extension/wa.sync'
import { Route as ApiPublicExtensionWaDataRouteImport } from './routes/api/public/extension/wa.data'
import { Route as ApiPublicExtensionQuickRepliesUploadRouteImport } from './routes/api/public/extension/quick-replies.upload'
import { Route as ApiPublicExtensionQuickRepliesIdRouteImport } from './routes/api/public/extension/quick-replies.$id'
import { Route as ApiPublicExtensionJobsNextRouteImport } from './routes/api/public/extension/jobs.next'
import { Route as ApiPublicExtensionJobsIdRouteImport } from './routes/api/public/extension/jobs.$id'
import { Route as ApiPublicExtensionFunnelsIdRouteImport } from './routes/api/public/extension/funnels.$id'
import { Route as ApiPublicExtensionFunnelCardsScheduleRouteImport } from './routes/api/public/extension/funnel-cards.schedule'
import { Route as ApiPublicExtensionCustomersImportRouteImport } from './routes/api/public/extension/customers.import'
import { Route as ApiPublicExtensionCustomersIdRouteImport } from './routes/api/public/extension/customers.$id'
import { Route as ApiPublicExtensionCampaignsIdRouteImport } from './routes/api/public/extension/campaigns.$id'

const PoliticasRoute = PoliticasRouteImport.update({
  id: '/politicas',
  path: '/politicas',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const BaixarRoute = BaixarRouteImport.update({
  id: '/baixar',
  path: '/baixar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRetornoRoute = AssinarRetornoRouteImport.update({
  id: '/retorno',
  path: '/retorno',
  getParentRoute: () => AssinarRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/admin/whatsapp',
  path: '/admin/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSignupRoute = ApiPublicSignupRouteImport.update({
  id: '/api/public/signup',
  path: '/api/public/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappSignupCallbackRoute =
  ApiPublicWhatsappSignupCallbackRouteImport.update({
    id: '/api/public/whatsapp/signup-callback',
    path: '/api/public/whatsapp/signup-callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDispatchJobsRoute =
  ApiPublicHooksDispatchJobsRouteImport.update({
    id: '/api/public/hooks/dispatch-jobs',
    path: '/api/public/hooks/dispatch-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionQuickRepliesRoute =
  ApiPublicExtensionQuickRepliesRouteImport.update({
    id: '/api/public/extension/quick-replies',
    path: '/api/public/extension/quick-replies',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionPairRoute = ApiPublicExtensionPairRouteImport.update({
  id: '/api/public/extension/pair',
  path: '/api/public/extension/pair',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionMetaRoute = ApiPublicExtensionMetaRouteImport.update({
  id: '/api/public/extension/meta',
  path: '/api/public/extension/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensionFunnelsRoute =
  ApiPublicExtensionFunnelsRouteImport.update({
    id: '/api/public/extension/funnels',
    path: '/api/public/extension/funnels',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionFunnelCardsRoute =
  ApiPublicExtensionFunnelCardsRouteImport.update({
    id: '/api/public/extension/funnel-cards',
    path: '/api/public/extension/funnel-cards',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionCustomersRoute =
  ApiPublicExtensionCustomersRouteImport.update({
    id: '/api/public/extension/customers',
    path: '/api/public/extension/customers',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionCampaignsRoute =
  ApiPublicExtensionCampaignsRouteImport.update({
    id: '/api/public/extension/campaigns',
    path: '/api/public/extension/campaigns',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionBillingRoute =
  ApiPublicExtensionBillingRouteImport.update({
    id: '/api/public/extension/billing',
    path: '/api/public/extension/billing',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionWhatsappStatusRoute =
  ApiPublicExtensionWhatsappStatusRouteImport.update({
    id: '/api/public/extension/whatsapp/status',
    path: '/api/public/extension/whatsapp/status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionWhatsappProviderRoute =
  ApiPublicExtensionWhatsappProviderRouteImport.update({
    id: '/api/public/extension/whatsapp/provider',
    path: '/api/public/extension/whatsapp/provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionWhatsappDisconnectRoute =
  ApiPublicExtensionWhatsappDisconnectRouteImport.update({
    id: '/api/public/extension/whatsapp/disconnect',
    path: '/api/public/extension/whatsapp/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionWhatsappConnectRoute =
  ApiPublicExtensionWhatsappConnectRouteImport.update({
    id: '/api/public/extension/whatsapp/connect',
    path: '/api/public/extension/whatsapp/connect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionWaSyncRoute =
  ApiPublicExtensionWaSyncRouteImport.update({
    id: '/api/public/extension/wa/sync',
    path: '/api/public/extension/wa/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionWaDataRoute =
  ApiPublicExtensionWaDataRouteImport.update({
    id: '/api/public/extension/wa/data',
    path: '/api/public/extension/wa/data',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionQuickRepliesUploadRoute =
  ApiPublicExtensionQuickRepliesUploadRouteImport.update({
    id: '/upload',
    path: '/upload',
    getParentRoute: () => ApiPublicExtensionQuickRepliesRoute,
  } as any)
const ApiPublicExtensionQuickRepliesIdRoute =
  ApiPublicExtensionQuickRepliesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicExtensionQuickRepliesRoute,
  } as any)
const ApiPublicExtensionJobsNextRoute =
  ApiPublicExtensionJobsNextRouteImport.update({
    id: '/api/public/extension/jobs/next',
    path: '/api/public/extension/jobs/next',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionJobsIdRoute =
  ApiPublicExtensionJobsIdRouteImport.update({
    id: '/api/public/extension/jobs/$id',
    path: '/api/public/extension/jobs/$id',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExtensionFunnelsIdRoute =
  ApiPublicExtensionFunnelsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicExtensionFunnelsRoute,
  } as any)
const ApiPublicExtensionFunnelCardsScheduleRoute =
  ApiPublicExtensionFunnelCardsScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => ApiPublicExtensionFunnelCardsRoute,
  } as any)
const ApiPublicExtensionCustomersImportRoute =
  ApiPublicExtensionCustomersImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => ApiPublicExtensionCustomersRoute,
  } as any)
const ApiPublicExtensionCustomersIdRoute =
  ApiPublicExtensionCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicExtensionCustomersRoute,
  } as any)
const ApiPublicExtensionCampaignsIdRoute =
  ApiPublicExtensionCampaignsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ApiPublicExtensionCampaignsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRouteWithChildren
  '/baixar': typeof BaixarRoute
  '/instalar': typeof InstalarRoute
  '/painel': typeof PainelRoute
  '/politicas': typeof PoliticasRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/assinar/retorno': typeof AssinarRetornoRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/extension/billing': typeof ApiPublicExtensionBillingRoute
  '/api/public/extension/campaigns': typeof ApiPublicExtensionCampaignsRouteWithChildren
  '/api/public/extension/customers': typeof ApiPublicExtensionCustomersRouteWithChildren
  '/api/public/extension/funnel-cards': typeof ApiPublicExtensionFunnelCardsRouteWithChildren
  '/api/public/extension/funnels': typeof ApiPublicExtensionFunnelsRouteWithChildren
  '/api/public/extension/meta': typeof ApiPublicExtensionMetaRoute
  '/api/public/extension/pair': typeof ApiPublicExtensionPairRoute
  '/api/public/extension/quick-replies': typeof ApiPublicExtensionQuickRepliesRouteWithChildren
  '/api/public/hooks/dispatch-jobs': typeof ApiPublicHooksDispatchJobsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/signup-callback': typeof ApiPublicWhatsappSignupCallbackRoute
  '/api/public/extension/campaigns/$id': typeof ApiPublicExtensionCampaignsIdRoute
  '/api/public/extension/customers/$id': typeof ApiPublicExtensionCustomersIdRoute
  '/api/public/extension/customers/import': typeof ApiPublicExtensionCustomersImportRoute
  '/api/public/extension/funnel-cards/schedule': typeof ApiPublicExtensionFunnelCardsScheduleRoute
  '/api/public/extension/funnels/$id': typeof ApiPublicExtensionFunnelsIdRoute
  '/api/public/extension/jobs/$id': typeof ApiPublicExtensionJobsIdRoute
  '/api/public/extension/jobs/next': typeof ApiPublicExtensionJobsNextRoute
  '/api/public/extension/quick-replies/$id': typeof ApiPublicExtensionQuickRepliesIdRoute
  '/api/public/extension/quick-replies/upload': typeof ApiPublicExtensionQuickRepliesUploadRoute
  '/api/public/extension/wa/data': typeof ApiPublicExtensionWaDataRoute
  '/api/public/extension/wa/sync': typeof ApiPublicExtensionWaSyncRoute
  '/api/public/extension/whatsapp/connect': typeof ApiPublicExtensionWhatsappConnectRoute
  '/api/public/extension/whatsapp/disconnect': typeof ApiPublicExtensionWhatsappDisconnectRoute
  '/api/public/extension/whatsapp/provider': typeof ApiPublicExtensionWhatsappProviderRoute
  '/api/public/extension/whatsapp/status': typeof ApiPublicExtensionWhatsappStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRouteWithChildren
  '/baixar': typeof BaixarRoute
  '/instalar': typeof InstalarRoute
  '/painel': typeof PainelRoute
  '/politicas': typeof PoliticasRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/assinar/retorno': typeof AssinarRetornoRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/extension/billing': typeof ApiPublicExtensionBillingRoute
  '/api/public/extension/campaigns': typeof ApiPublicExtensionCampaignsRouteWithChildren
  '/api/public/extension/customers': typeof ApiPublicExtensionCustomersRouteWithChildren
  '/api/public/extension/funnel-cards': typeof ApiPublicExtensionFunnelCardsRouteWithChildren
  '/api/public/extension/funnels': typeof ApiPublicExtensionFunnelsRouteWithChildren
  '/api/public/extension/meta': typeof ApiPublicExtensionMetaRoute
  '/api/public/extension/pair': typeof ApiPublicExtensionPairRoute
  '/api/public/extension/quick-replies': typeof ApiPublicExtensionQuickRepliesRouteWithChildren
  '/api/public/hooks/dispatch-jobs': typeof ApiPublicHooksDispatchJobsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/signup-callback': typeof ApiPublicWhatsappSignupCallbackRoute
  '/api/public/extension/campaigns/$id': typeof ApiPublicExtensionCampaignsIdRoute
  '/api/public/extension/customers/$id': typeof ApiPublicExtensionCustomersIdRoute
  '/api/public/extension/customers/import': typeof ApiPublicExtensionCustomersImportRoute
  '/api/public/extension/funnel-cards/schedule': typeof ApiPublicExtensionFunnelCardsScheduleRoute
  '/api/public/extension/funnels/$id': typeof ApiPublicExtensionFunnelsIdRoute
  '/api/public/extension/jobs/$id': typeof ApiPublicExtensionJobsIdRoute
  '/api/public/extension/jobs/next': typeof ApiPublicExtensionJobsNextRoute
  '/api/public/extension/quick-replies/$id': typeof ApiPublicExtensionQuickRepliesIdRoute
  '/api/public/extension/quick-replies/upload': typeof ApiPublicExtensionQuickRepliesUploadRoute
  '/api/public/extension/wa/data': typeof ApiPublicExtensionWaDataRoute
  '/api/public/extension/wa/sync': typeof ApiPublicExtensionWaSyncRoute
  '/api/public/extension/whatsapp/connect': typeof ApiPublicExtensionWhatsappConnectRoute
  '/api/public/extension/whatsapp/disconnect': typeof ApiPublicExtensionWhatsappDisconnectRoute
  '/api/public/extension/whatsapp/provider': typeof ApiPublicExtensionWhatsappProviderRoute
  '/api/public/extension/whatsapp/status': typeof ApiPublicExtensionWhatsappStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRouteWithChildren
  '/baixar': typeof BaixarRoute
  '/instalar': typeof InstalarRoute
  '/painel': typeof PainelRoute
  '/politicas': typeof PoliticasRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/assinar/retorno': typeof AssinarRetornoRoute
  '/api/public/signup': typeof ApiPublicSignupRoute
  '/api/public/extension/billing': typeof ApiPublicExtensionBillingRoute
  '/api/public/extension/campaigns': typeof ApiPublicExtensionCampaignsRouteWithChildren
  '/api/public/extension/customers': typeof ApiPublicExtensionCustomersRouteWithChildren
  '/api/public/extension/funnel-cards': typeof ApiPublicExtensionFunnelCardsRouteWithChildren
  '/api/public/extension/funnels': typeof ApiPublicExtensionFunnelsRouteWithChildren
  '/api/public/extension/meta': typeof ApiPublicExtensionMetaRoute
  '/api/public/extension/pair': typeof ApiPublicExtensionPairRoute
  '/api/public/extension/quick-replies': typeof ApiPublicExtensionQuickRepliesRouteWithChildren
  '/api/public/hooks/dispatch-jobs': typeof ApiPublicHooksDispatchJobsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/whatsapp/signup-callback': typeof ApiPublicWhatsappSignupCallbackRoute
  '/api/public/extension/campaigns/$id': typeof ApiPublicExtensionCampaignsIdRoute
  '/api/public/extension/customers/$id': typeof ApiPublicExtensionCustomersIdRoute
  '/api/public/extension/customers/import': typeof ApiPublicExtensionCustomersImportRoute
  '/api/public/extension/funnel-cards/schedule': typeof ApiPublicExtensionFunnelCardsScheduleRoute
  '/api/public/extension/funnels/$id': typeof ApiPublicExtensionFunnelsIdRoute
  '/api/public/extension/jobs/$id': typeof ApiPublicExtensionJobsIdRoute
  '/api/public/extension/jobs/next': typeof ApiPublicExtensionJobsNextRoute
  '/api/public/extension/quick-replies/$id': typeof ApiPublicExtensionQuickRepliesIdRoute
  '/api/public/extension/quick-replies/upload': typeof ApiPublicExtensionQuickRepliesUploadRoute
  '/api/public/extension/wa/data': typeof ApiPublicExtensionWaDataRoute
  '/api/public/extension/wa/sync': typeof ApiPublicExtensionWaSyncRoute
  '/api/public/extension/whatsapp/connect': typeof ApiPublicExtensionWhatsappConnectRoute
  '/api/public/extension/whatsapp/disconnect': typeof ApiPublicExtensionWhatsappDisconnectRoute
  '/api/public/extension/whatsapp/provider': typeof ApiPublicExtensionWhatsappProviderRoute
  '/api/public/extension/whatsapp/status': typeof ApiPublicExtensionWhatsappStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinar'
    | '/baixar'
    | '/instalar'
    | '/painel'
    | '/politicas'
    | '/admin/whatsapp'
    | '/assinar/retorno'
    | '/api/public/signup'
    | '/api/public/extension/billing'
    | '/api/public/extension/campaigns'
    | '/api/public/extension/customers'
    | '/api/public/extension/funnel-cards'
    | '/api/public/extension/funnels'
    | '/api/public/extension/meta'
    | '/api/public/extension/pair'
    | '/api/public/extension/quick-replies'
    | '/api/public/hooks/dispatch-jobs'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/signup-callback'
    | '/api/public/extension/campaigns/$id'
    | '/api/public/extension/customers/$id'
    | '/api/public/extension/customers/import'
    | '/api/public/extension/funnel-cards/schedule'
    | '/api/public/extension/funnels/$id'
    | '/api/public/extension/jobs/$id'
    | '/api/public/extension/jobs/next'
    | '/api/public/extension/quick-replies/$id'
    | '/api/public/extension/quick-replies/upload'
    | '/api/public/extension/wa/data'
    | '/api/public/extension/wa/sync'
    | '/api/public/extension/whatsapp/connect'
    | '/api/public/extension/whatsapp/disconnect'
    | '/api/public/extension/whatsapp/provider'
    | '/api/public/extension/whatsapp/status'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar'
    | '/baixar'
    | '/instalar'
    | '/painel'
    | '/politicas'
    | '/admin/whatsapp'
    | '/assinar/retorno'
    | '/api/public/signup'
    | '/api/public/extension/billing'
    | '/api/public/extension/campaigns'
    | '/api/public/extension/customers'
    | '/api/public/extension/funnel-cards'
    | '/api/public/extension/funnels'
    | '/api/public/extension/meta'
    | '/api/public/extension/pair'
    | '/api/public/extension/quick-replies'
    | '/api/public/hooks/dispatch-jobs'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/signup-callback'
    | '/api/public/extension/campaigns/$id'
    | '/api/public/extension/customers/$id'
    | '/api/public/extension/customers/import'
    | '/api/public/extension/funnel-cards/schedule'
    | '/api/public/extension/funnels/$id'
    | '/api/public/extension/jobs/$id'
    | '/api/public/extension/jobs/next'
    | '/api/public/extension/quick-replies/$id'
    | '/api/public/extension/quick-replies/upload'
    | '/api/public/extension/wa/data'
    | '/api/public/extension/wa/sync'
    | '/api/public/extension/whatsapp/connect'
    | '/api/public/extension/whatsapp/disconnect'
    | '/api/public/extension/whatsapp/provider'
    | '/api/public/extension/whatsapp/status'
  id:
    | '__root__'
    | '/'
    | '/assinar'
    | '/baixar'
    | '/instalar'
    | '/painel'
    | '/politicas'
    | '/admin/whatsapp'
    | '/assinar/retorno'
    | '/api/public/signup'
    | '/api/public/extension/billing'
    | '/api/public/extension/campaigns'
    | '/api/public/extension/customers'
    | '/api/public/extension/funnel-cards'
    | '/api/public/extension/funnels'
    | '/api/public/extension/meta'
    | '/api/public/extension/pair'
    | '/api/public/extension/quick-replies'
    | '/api/public/hooks/dispatch-jobs'
    | '/api/public/payments/webhook'
    | '/api/public/whatsapp/signup-callback'
    | '/api/public/extension/campaigns/$id'
    | '/api/public/extension/customers/$id'
    | '/api/public/extension/customers/import'
    | '/api/public/extension/funnel-cards/schedule'
    | '/api/public/extension/funnels/$id'
    | '/api/public/extension/jobs/$id'
    | '/api/public/extension/jobs/next'
    | '/api/public/extension/quick-replies/$id'
    | '/api/public/extension/quick-replies/upload'
    | '/api/public/extension/wa/data'
    | '/api/public/extension/wa/sync'
    | '/api/public/extension/whatsapp/connect'
    | '/api/public/extension/whatsapp/disconnect'
    | '/api/public/extension/whatsapp/provider'
    | '/api/public/extension/whatsapp/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinarRoute: typeof AssinarRouteWithChildren
  BaixarRoute: typeof BaixarRoute
  InstalarRoute: typeof InstalarRoute
  PainelRoute: typeof PainelRoute
  PoliticasRoute: typeof PoliticasRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  ApiPublicSignupRoute: typeof ApiPublicSignupRoute
  ApiPublicExtensionBillingRoute: typeof ApiPublicExtensionBillingRoute
  ApiPublicExtensionCampaignsRoute: typeof ApiPublicExtensionCampaignsRouteWithChildren
  ApiPublicExtensionCustomersRoute: typeof ApiPublicExtensionCustomersRouteWithChildren
  ApiPublicExtensionFunnelCardsRoute: typeof ApiPublicExtensionFunnelCardsRouteWithChildren
  ApiPublicExtensionFunnelsRoute: typeof ApiPublicExtensionFunnelsRouteWithChildren
  ApiPublicExtensionMetaRoute: typeof ApiPublicExtensionMetaRoute
  ApiPublicExtensionPairRoute: typeof ApiPublicExtensionPairRoute
  ApiPublicExtensionQuickRepliesRoute: typeof ApiPublicExtensionQuickRepliesRouteWithChildren
  ApiPublicHooksDispatchJobsRoute: typeof ApiPublicHooksDispatchJobsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWhatsappSignupCallbackRoute: typeof ApiPublicWhatsappSignupCallbackRoute
  ApiPublicExtensionJobsIdRoute: typeof ApiPublicExtensionJobsIdRoute
  ApiPublicExtensionJobsNextRoute: typeof ApiPublicExtensionJobsNextRoute
  ApiPublicExtensionWaDataRoute: typeof ApiPublicExtensionWaDataRoute
  ApiPublicExtensionWaSyncRoute: typeof ApiPublicExtensionWaSyncRoute
  ApiPublicExtensionWhatsappConnectRoute: typeof ApiPublicExtensionWhatsappConnectRoute
  ApiPublicExtensionWhatsappDisconnectRoute: typeof ApiPublicExtensionWhatsappDisconnectRoute
  ApiPublicExtensionWhatsappProviderRoute: typeof ApiPublicExtensionWhatsappProviderRoute
  ApiPublicExtensionWhatsappStatusRoute: typeof ApiPublicExtensionWhatsappStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/politicas': {
      id: '/politicas'
      path: '/politicas'
      fullPath: '/politicas'
      preLoaderRoute: typeof PoliticasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baixar': {
      id: '/baixar'
      path: '/baixar'
      fullPath: '/baixar'
      preLoaderRoute: typeof BaixarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar/retorno': {
      id: '/assinar/retorno'
      path: '/retorno'
      fullPath: '/assinar/retorno'
      preLoaderRoute: typeof AssinarRetornoRouteImport
      parentRoute: typeof AssinarRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/admin/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signup': {
      id: '/api/public/signup'
      path: '/api/public/signup'
      fullPath: '/api/public/signup'
      preLoaderRoute: typeof ApiPublicSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/signup-callback': {
      id: '/api/public/whatsapp/signup-callback'
      path: '/api/public/whatsapp/signup-callback'
      fullPath: '/api/public/whatsapp/signup-callback'
      preLoaderRoute: typeof ApiPublicWhatsappSignupCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/dispatch-jobs': {
      id: '/api/public/hooks/dispatch-jobs'
      path: '/api/public/hooks/dispatch-jobs'
      fullPath: '/api/public/hooks/dispatch-jobs'
      preLoaderRoute: typeof ApiPublicHooksDispatchJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/quick-replies': {
      id: '/api/public/extension/quick-replies'
      path: '/api/public/extension/quick-replies'
      fullPath: '/api/public/extension/quick-replies'
      preLoaderRoute: typeof ApiPublicExtensionQuickRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/pair': {
      id: '/api/public/extension/pair'
      path: '/api/public/extension/pair'
      fullPath: '/api/public/extension/pair'
      preLoaderRoute: typeof ApiPublicExtensionPairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/meta': {
      id: '/api/public/extension/meta'
      path: '/api/public/extension/meta'
      fullPath: '/api/public/extension/meta'
      preLoaderRoute: typeof ApiPublicExtensionMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/funnels': {
      id: '/api/public/extension/funnels'
      path: '/api/public/extension/funnels'
      fullPath: '/api/public/extension/funnels'
      preLoaderRoute: typeof ApiPublicExtensionFunnelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/funnel-cards': {
      id: '/api/public/extension/funnel-cards'
      path: '/api/public/extension/funnel-cards'
      fullPath: '/api/public/extension/funnel-cards'
      preLoaderRoute: typeof ApiPublicExtensionFunnelCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/customers': {
      id: '/api/public/extension/customers'
      path: '/api/public/extension/customers'
      fullPath: '/api/public/extension/customers'
      preLoaderRoute: typeof ApiPublicExtensionCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/campaigns': {
      id: '/api/public/extension/campaigns'
      path: '/api/public/extension/campaigns'
      fullPath: '/api/public/extension/campaigns'
      preLoaderRoute: typeof ApiPublicExtensionCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/billing': {
      id: '/api/public/extension/billing'
      path: '/api/public/extension/billing'
      fullPath: '/api/public/extension/billing'
      preLoaderRoute: typeof ApiPublicExtensionBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/whatsapp/status': {
      id: '/api/public/extension/whatsapp/status'
      path: '/api/public/extension/whatsapp/status'
      fullPath: '/api/public/extension/whatsapp/status'
      preLoaderRoute: typeof ApiPublicExtensionWhatsappStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/whatsapp/provider': {
      id: '/api/public/extension/whatsapp/provider'
      path: '/api/public/extension/whatsapp/provider'
      fullPath: '/api/public/extension/whatsapp/provider'
      preLoaderRoute: typeof ApiPublicExtensionWhatsappProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/whatsapp/disconnect': {
      id: '/api/public/extension/whatsapp/disconnect'
      path: '/api/public/extension/whatsapp/disconnect'
      fullPath: '/api/public/extension/whatsapp/disconnect'
      preLoaderRoute: typeof ApiPublicExtensionWhatsappDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/whatsapp/connect': {
      id: '/api/public/extension/whatsapp/connect'
      path: '/api/public/extension/whatsapp/connect'
      fullPath: '/api/public/extension/whatsapp/connect'
      preLoaderRoute: typeof ApiPublicExtensionWhatsappConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/wa/sync': {
      id: '/api/public/extension/wa/sync'
      path: '/api/public/extension/wa/sync'
      fullPath: '/api/public/extension/wa/sync'
      preLoaderRoute: typeof ApiPublicExtensionWaSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/wa/data': {
      id: '/api/public/extension/wa/data'
      path: '/api/public/extension/wa/data'
      fullPath: '/api/public/extension/wa/data'
      preLoaderRoute: typeof ApiPublicExtensionWaDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/quick-replies/upload': {
      id: '/api/public/extension/quick-replies/upload'
      path: '/upload'
      fullPath: '/api/public/extension/quick-replies/upload'
      preLoaderRoute: typeof ApiPublicExtensionQuickRepliesUploadRouteImport
      parentRoute: typeof ApiPublicExtensionQuickRepliesRoute
    }
    '/api/public/extension/quick-replies/$id': {
      id: '/api/public/extension/quick-replies/$id'
      path: '/$id'
      fullPath: '/api/public/extension/quick-replies/$id'
      preLoaderRoute: typeof ApiPublicExtensionQuickRepliesIdRouteImport
      parentRoute: typeof ApiPublicExtensionQuickRepliesRoute
    }
    '/api/public/extension/jobs/next': {
      id: '/api/public/extension/jobs/next'
      path: '/api/public/extension/jobs/next'
      fullPath: '/api/public/extension/jobs/next'
      preLoaderRoute: typeof ApiPublicExtensionJobsNextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/jobs/$id': {
      id: '/api/public/extension/jobs/$id'
      path: '/api/public/extension/jobs/$id'
      fullPath: '/api/public/extension/jobs/$id'
      preLoaderRoute: typeof ApiPublicExtensionJobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extension/funnels/$id': {
      id: '/api/public/extension/funnels/$id'
      path: '/$id'
      fullPath: '/api/public/extension/funnels/$id'
      preLoaderRoute: typeof ApiPublicExtensionFunnelsIdRouteImport
      parentRoute: typeof ApiPublicExtensionFunnelsRoute
    }
    '/api/public/extension/funnel-cards/schedule': {
      id: '/api/public/extension/funnel-cards/schedule'
      path: '/schedule'
      fullPath: '/api/public/extension/funnel-cards/schedule'
      preLoaderRoute: typeof ApiPublicExtensionFunnelCardsScheduleRouteImport
      parentRoute: typeof ApiPublicExtensionFunnelCardsRoute
    }
    '/api/public/extension/customers/import': {
      id: '/api/public/extension/customers/import'
      path: '/import'
      fullPath: '/api/public/extension/customers/import'
      preLoaderRoute: typeof ApiPublicExtensionCustomersImportRouteImport
      parentRoute: typeof ApiPublicExtensionCustomersRoute
    }
    '/api/public/extension/customers/$id': {
      id: '/api/public/extension/customers/$id'
      path: '/$id'
      fullPath: '/api/public/extension/customers/$id'
      preLoaderRoute: typeof ApiPublicExtensionCustomersIdRouteImport
      parentRoute: typeof ApiPublicExtensionCustomersRoute
    }
    '/api/public/extension/campaigns/$id': {
      id: '/api/public/extension/campaigns/$id'
      path: '/$id'
      fullPath: '/api/public/extension/campaigns/$id'
      preLoaderRoute: typeof ApiPublicExtensionCampaignsIdRouteImport
      parentRoute: typeof ApiPublicExtensionCampaignsRoute
    }
  }
}

interface AssinarRouteChildren {
  AssinarRetornoRoute: typeof AssinarRetornoRoute
}

const AssinarRouteChildren: AssinarRouteChildren = {
  AssinarRetornoRoute: AssinarRetornoRoute,
}

const AssinarRouteWithChildren =
  AssinarRoute._addFileChildren(AssinarRouteChildren)

interface ApiPublicExtensionCampaignsRouteChildren {
  ApiPublicExtensionCampaignsIdRoute: typeof ApiPublicExtensionCampaignsIdRoute
}

const ApiPublicExtensionCampaignsRouteChildren: ApiPublicExtensionCampaignsRouteChildren =
  {
    ApiPublicExtensionCampaignsIdRoute: ApiPublicExtensionCampaignsIdRoute,
  }

const ApiPublicExtensionCampaignsRouteWithChildren =
  ApiPublicExtensionCampaignsRoute._addFileChildren(
    ApiPublicExtensionCampaignsRouteChildren,
  )

interface ApiPublicExtensionCustomersRouteChildren {
  ApiPublicExtensionCustomersIdRoute: typeof ApiPublicExtensionCustomersIdRoute
  ApiPublicExtensionCustomersImportRoute: typeof ApiPublicExtensionCustomersImportRoute
}

const ApiPublicExtensionCustomersRouteChildren: ApiPublicExtensionCustomersRouteChildren =
  {
    ApiPublicExtensionCustomersIdRoute: ApiPublicExtensionCustomersIdRoute,
    ApiPublicExtensionCustomersImportRoute:
      ApiPublicExtensionCustomersImportRoute,
  }

const ApiPublicExtensionCustomersRouteWithChildren =
  ApiPublicExtensionCustomersRoute._addFileChildren(
    ApiPublicExtensionCustomersRouteChildren,
  )

interface ApiPublicExtensionFunnelCardsRouteChildren {
  ApiPublicExtensionFunnelCardsScheduleRoute: typeof ApiPublicExtensionFunnelCardsScheduleRoute
}

const ApiPublicExtensionFunnelCardsRouteChildren: ApiPublicExtensionFunnelCardsRouteChildren =
  {
    ApiPublicExtensionFunnelCardsScheduleRoute:
      ApiPublicExtensionFunnelCardsScheduleRoute,
  }

const ApiPublicExtensionFunnelCardsRouteWithChildren =
  ApiPublicExtensionFunnelCardsRoute._addFileChildren(
    ApiPublicExtensionFunnelCardsRouteChildren,
  )

interface ApiPublicExtensionFunnelsRouteChildren {
  ApiPublicExtensionFunnelsIdRoute: typeof ApiPublicExtensionFunnelsIdRoute
}

const ApiPublicExtensionFunnelsRouteChildren: ApiPublicExtensionFunnelsRouteChildren =
  {
    ApiPublicExtensionFunnelsIdRoute: ApiPublicExtensionFunnelsIdRoute,
  }

const ApiPublicExtensionFunnelsRouteWithChildren =
  ApiPublicExtensionFunnelsRoute._addFileChildren(
    ApiPublicExtensionFunnelsRouteChildren,
  )

interface ApiPublicExtensionQuickRepliesRouteChildren {
  ApiPublicExtensionQuickRepliesIdRoute: typeof ApiPublicExtensionQuickRepliesIdRoute
  ApiPublicExtensionQuickRepliesUploadRoute: typeof ApiPublicExtensionQuickRepliesUploadRoute
}

const ApiPublicExtensionQuickRepliesRouteChildren: ApiPublicExtensionQuickRepliesRouteChildren =
  {
    ApiPublicExtensionQuickRepliesIdRoute:
      ApiPublicExtensionQuickRepliesIdRoute,
    ApiPublicExtensionQuickRepliesUploadRoute:
      ApiPublicExtensionQuickRepliesUploadRoute,
  }

const ApiPublicExtensionQuickRepliesRouteWithChildren =
  ApiPublicExtensionQuickRepliesRoute._addFileChildren(
    ApiPublicExtensionQuickRepliesRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinarRoute: AssinarRouteWithChildren,
  BaixarRoute: BaixarRoute,
  InstalarRoute: InstalarRoute,
  PainelRoute: PainelRoute,
  PoliticasRoute: PoliticasRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  ApiPublicSignupRoute: ApiPublicSignupRoute,
  ApiPublicExtensionBillingRoute: ApiPublicExtensionBillingRoute,
  ApiPublicExtensionCampaignsRoute:
    ApiPublicExtensionCampaignsRouteWithChildren,
  ApiPublicExtensionCustomersRoute:
    ApiPublicExtensionCustomersRouteWithChildren,
  ApiPublicExtensionFunnelCardsRoute:
    ApiPublicExtensionFunnelCardsRouteWithChildren,
  ApiPublicExtensionFunnelsRoute: ApiPublicExtensionFunnelsRouteWithChildren,
  ApiPublicExtensionMetaRoute: ApiPublicExtensionMetaRoute,
  ApiPublicExtensionPairRoute: ApiPublicExtensionPairRoute,
  ApiPublicExtensionQuickRepliesRoute:
    ApiPublicExtensionQuickRepliesRouteWithChildren,
  ApiPublicHooksDispatchJobsRoute: ApiPublicHooksDispatchJobsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWhatsappSignupCallbackRoute: ApiPublicWhatsappSignupCallbackRoute,
  ApiPublicExtensionJobsIdRoute: ApiPublicExtensionJobsIdRoute,
  ApiPublicExtensionJobsNextRoute: ApiPublicExtensionJobsNextRoute,
  ApiPublicExtensionWaDataRoute: ApiPublicExtensionWaDataRoute,
  ApiPublicExtensionWaSyncRoute: ApiPublicExtensionWaSyncRoute,
  ApiPublicExtensionWhatsappConnectRoute:
    ApiPublicExtensionWhatsappConnectRoute,
  ApiPublicExtensionWhatsappDisconnectRoute:
    ApiPublicExtensionWhatsappDisconnectRoute,
  ApiPublicExtensionWhatsappProviderRoute:
    ApiPublicExtensionWhatsappProviderRoute,
  ApiPublicExtensionWhatsappStatusRoute: ApiPublicExtensionWhatsappStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
